name: build_and_publish_image
run-name: ${{ github.event.release.tag_name }}

on:
  release:
    types: [published]

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: edcb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read EDCB release
        run: echo "EDCB_RELEASE=$(cat .edcb-release | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.EDCB_RELEASE }}-latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          build-args: |
            EDCB_RELEASE=${{ env.EDCB_RELEASE }}
